name: stealth
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0<3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  intl_phone_field: ^3.1.0
  pinput: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/

analyzer:
  enable-experiment:
   - non-nullable